### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by weiransoft** [CiscoCloud/nginx-mantlui#29]
The glide install error:

Step 11 : RUN glide install
 ---> Running in 0588590f28c8
[WARN]	The name listed in the config file (main) does not match the current location (github.com/containous/traefik)
[WARN]	Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching github.com/alecthomas/template.
[INFO]	--> Fetching github.com/alecthomas/units.
[INFO]	--> Fetching github.com/boltdb/bolt.
[INFO]	--> Fetching github.com/BurntSushi/toml.
[INFO]	--> Fetching github.com/BurntSushi/ty.
[INFO]	--> Fetching github.com/cenkalti/backoff.
[INFO]	--> Fetching github.com/codahale/hdrhistogram.
[INFO]	--> Fetching github.com/codegangsta/cli.
[INFO]	--> Fetching github.com/codegangsta/negroni.
[INFO]	--> Fetching github.com/coreos/go-etcd.
[INFO]	--> Fetching github.com/containous/oxy.
[WARN]	Unable to checkout github.com/boltdb/bolt
[ERROR]	Update failed for github.com/boltdb/bolt: Unable to get repository
[INFO]	--> Fetching github.com/donovanhide/eventsource.
[INFO]	--> Fetching github.com/davecgh/go-spew.
[INFO]	--> Fetching github.com/docker/distribution.
[INFO]	--> Fetching github.com/docker/docker.
[INFO]	--> Fetching github.com/docker/go-connections.
[WARN]	Unable to checkout github.com/cenkalti/backoff
[ERROR]	Update failed for github.com/cenkalti/backoff: Unable to get repository
[INFO]	--> Fetching github.com/elazarl/go-bindata-assetfs.
[INFO]	--> Fetching github.com/docker/go-units.
[WARN]	Unable to checkout github.com/codegangsta/cli
[ERROR]	Update failed for github.com/codegangsta/cli: Unable to get repository
[INFO]	--> Fetching github.com/flynn/go-shlex.
[INFO]	--> Fetching github.com/docker/libcompose.
[INFO]	--> Fetching github.com/docker/libkv.
[INFO]	--> Fetching github.com/docker/libtrust.
[WARN]	Unable to checkout github.com/coreos/go-etcd
[ERROR]	Update failed for github.com/coreos/go-etcd: Unable to get repository
[INFO]	--> Fetching github.com/gambol99/go-marathon.
[INFO]	--> Fetching github.com/docker/engine-api.
[WARN]	Unable to checkout github.com/alecthomas/units
[ERROR]	Update failed for github.com/alecthomas/units: Unable to get repository
[INFO]	--> Fetching github.com/go-check/check.
[WARN]	Unable to checkout github.com/codahale/hdrhistogram
[ERROR]	Update failed for github.com/codahale/hdrhistogram: Unable to get repository
[WARN]	Unable to checkout github.com/docker/go-connections
[ERROR]	Update failed for github.com/docker/go-connections: Unable to get repository
[INFO]	--> Fetching github.com/google/go-querystring.
[INFO]	--> Fetching github.com/golang/glog.
[WARN]	Unable to checkout github.com/BurntSushi/toml
[ERROR]	Update failed for github.com/BurntSushi/toml: Unable to get repository
[INFO]	--> Fetching github.com/gorilla/context.
[WARN]	Unable to checkout github.com/davecgh/go-spew
[ERROR]	Update failed for github.com/davecgh/go-spew: Unable to get repository
[INFO]	--> Fetching github.com/gorilla/handlers.
[WARN]	Unable to checkout github.com/elazarl/go-bindata-assetfs
[ERROR]	Update failed for github.com/elazarl/go-bindata-assetfs: Unable to get repository
[INFO]	--> Fetching github.com/gorilla/mux.
[WARN]	Unable to checkout github.com/docker/libcompose
[ERROR]	Update failed for github.com/docker/libcompose: Unable to get repository
[INFO]	--> Fetching github.com/gorilla/websocket.
[WARN]	Unable to checkout github.com/flynn/go-shlex
[ERROR]	Update failed for github.com/flynn/go-shlex: Unable to get repository
[WARN]	Unable to checkout github.com/gambol99/go-marathon
[ERROR]	Update failed for github.com/gambol99/go-marathon: Unable to get repository
[INFO]	--> Fetching github.com/hashicorp/hcl.
[INFO]	--> Fetching github.com/hashicorp/consul.
[WARN]	Unable to checkout github.com/go-check/check
[ERROR]	Update failed for github.com/go-check/check: Unable to get repository
[INFO]	--> Fetching github.com/inconshreveable/mousetrap.
[WARN]	Unable to checkout github.com/docker/libkv
[ERROR]	Update failed for github.com/docker/libkv: Unable to get repository
[INFO]	--> Fetching github.com/kr/pretty.
[WARN]	Unable to checkout github.com/docker/libtrust
[ERROR]	Update failed for github.com/docker/libtrust: Unable to get repository
[INFO]	--> Fetching github.com/kr/text.
[WARN]	Unable to checkout github.com/codegangsta/negroni
[ERROR]	Update failed for github.com/codegangsta/negroni: Unable to get repository
[INFO]	--> Fetching github.com/magiconair/properties.
[WARN]	Unable to checkout github.com/gorilla/mux
[ERROR]	Update failed for github.com/gorilla/mux: Unable to get repository
[INFO]	--> Fetching github.com/mailgun/log.
[WARN]	Unable to checkout github.com/alecthomas/template
[ERROR]	Update failed for github.com/alecthomas/template: Unable to get repository
[INFO]	--> Fetching github.com/mailgun/manners.
[WARN]	Unable to checkout github.com/inconshreveable/mousetrap
[ERROR]	Update failed for github.com/inconshreveable/mousetrap: Unable to get repository
[INFO]	--> Fetching github.com/mailgun/multibuf.
[WARN]	Unable to checkout github.com/mailgun/log
[ERROR]	Update failed for github.com/mailgun/log: Unable to get repository
[INFO]	--> Fetching github.com/mailgun/timetools.
[WARN]	Unable to checkout github.com/kr/pretty
[ERROR]	Update failed for github.com/kr/pretty: Unable to get repository
[INFO]	--> Fetching github.com/Microsoft/go-winio.
[WARN]	Unable to checkout github.com/containous/oxy
[ERROR]	Update failed for github.com/containous/oxy: Unable to get repository
[INFO]	--> Fetching github.com/miekg/dns.
[WARN]	Unable to checkout github.com/magiconair/properties
[ERROR]	Update failed for github.com/magiconair/properties: Unable to get repository
[INFO]	--> Fetching github.com/mitchellh/mapstructure.
[WARN]	Unable to checkout github.com/gorilla/handlers
[ERROR]	Update failed for github.com/gorilla/handlers: Unable to get repository
[INFO]	--> Fetching github.com/opencontainers/runc.
[WARN]	Unable to checkout github.com/mailgun/timetools
[ERROR]	Update failed for github.com/mailgun/timetools: Unable to get repository
[INFO]	--> Fetching github.com/pmezard/go-difflib.
[WARN]	Unable to checkout github.com/mitchellh/mapstructure
[ERROR]	Update failed for github.com/mitchellh/mapstructure: Unable to get repository
[INFO]	--> Fetching github.com/samuel/go-zookeeper.
[WARN]	Unable to checkout github.com/gorilla/context
[ERROR]	Update failed for github.com/gorilla/context: Unable to get repository
[INFO]	--> Fetching github.com/Sirupsen/logrus.
[WARN]	Unable to checkout github.com/pmezard/go-difflib
[ERROR]	Update failed for github.com/pmezard/go-difflib: Unable to get repository
[INFO]	--> Fetching github.com/spf13/cast.
[WARN]	Unable to checkout github.com/hashicorp/hcl
[ERROR]	Update failed for github.com/hashicorp/hcl: Unable to get repository
[INFO]	--> Fetching github.com/spf13/cobra.
[WARN]	Unable to checkout github.com/spf13/cast
[ERROR]	Update failed for github.com/spf13/cast: Unable to get repository
[INFO]	--> Fetching github.com/spf13/jwalterweatherman.
[WARN]	Unable to checkout github.com/spf13/cobra
[ERROR]	Update failed for github.com/spf13/cobra: Unable to get repository
[INFO]	--> Fetching github.com/spf13/pflag.
[WARN]	Unable to checkout github.com/spf13/pflag
[ERROR]	Update failed for github.com/spf13/pflag: Unable to get repository
[INFO]	--> Fetching github.com/spf13/viper.
[WARN]	Unable to checkout github.com/docker/distribution
[ERROR]	Update failed for github.com/docker/distribution: Unable to get repository
[INFO]	--> Fetching github.com/streamrail/concurrent-map.
[WARN]	Unable to checkout github.com/docker/engine-api
[ERROR]	Update failed for github.com/docker/engine-api: Unable to get repository
[INFO]	--> Fetching github.com/stretchr/objx.
[WARN]	Unable to checkout github.com/kr/text
[ERROR]	Update failed for github.com/kr/text: Unable to get repository
[INFO]	--> Fetching github.com/stretchr/testify.
[WARN]	Unable to checkout github.com/BurntSushi/ty
[ERROR]	Update failed for github.com/BurntSushi/ty: Unable to get repository
[WARN]	Unable to checkout github.com/docker/docker
[ERROR]	Update failed for github.com/docker/docker: Unable to get repository
[INFO]	--> Fetching github.com/unrolled/render.
[WARN]	Unable to checkout github.com/docker/go-units
[ERROR]	Update failed for github.com/docker/go-units: Unable to get repository
[INFO]	--> Fetching github.com/vdemeester/docker-events.
[WARN]	Unable to checkout github.com/mailgun/multibuf
[ERROR]	Update failed for github.com/mailgun/multibuf: Unable to get repository
[INFO]	--> Fetching github.com/vdemeester/libkermit.
[WARN]	Unable to checkout github.com/google/go-querystring
[ERROR]	Update failed for github.com/google/go-querystring: Unable to get repository
[INFO]	--> Fetching github.com/vdemeester/shakers.
[WARN]	Unable to checkout github.com/hashicorp/consul
[ERROR]	Update failed for github.com/hashicorp/consul: Unable to get repository
[INFO]	--> Fetching github.com/vulcand/oxy.
[WARN]	Unable to checkout github.com/miekg/dns
[ERROR]	Update failed for github.com/miekg/dns: Unable to get repository
[INFO]	--> Fetching github.com/vulcand/predicate.
[WARN]	Unable to checkout github.com/mailgun/manners
[ERROR]	Update failed for github.com/mailgun/manners: Unable to get repository
[INFO]	--> Fetching github.com/vulcand/route.
[WARN]	Unable to checkout github.com/samuel/go-zookeeper
[ERROR]	Update failed for github.com/samuel/go-zookeeper: Unable to get repository
[INFO]	--> Fetching github.com/vulcand/vulcand.
[WARN]	Unable to checkout github.com/golang/glog
[ERROR]	Update failed for github.com/golang/glog: Unable to get repository
[INFO]	--> Fetching github.com/wendal/errors.
[WARN]	Unable to checkout github.com/donovanhide/eventsource
[ERROR]	Update failed for github.com/donovanhide/eventsource: Unable to get repository
[INFO]	--> Fetching github.com/xenolf/lego.
[WARN]	Unable to checkout github.com/Microsoft/go-winio
[ERROR]	Update failed for github.com/Microsoft/go-winio: Unable to get repository
[INFO]	--> Fetching golang.org/x/crypto.
[WARN]	Unable to checkout github.com/opencontainers/runc
[ERROR]	Update failed for github.com/opencontainers/runc: Unable to get repository
[INFO]	--> Fetching golang.org/x/net.
[WARN]	Unable to checkout github.com/Sirupsen/logrus
[ERROR]	Update failed for github.com/Sirupsen/logrus: Unable to get repository
[INFO]	--> Fetching golang.org/x/sys.
[WARN]	Unable to checkout github.com/spf13/jwalterweatherman
[ERROR]	Update failed for github.com/spf13/jwalterweatherman: Unable to get repository
[INFO]	--> Fetching gopkg.in/alecthomas/kingpin.v2.
[INFO]	--> Fetching github.com/thoas/stats.
[WARN]	Unable to checkout github.com/gorilla/websocket
[ERROR]	Update failed for github.com/gorilla/websocket: Unable to get repository
[INFO]	--> Fetching gopkg.in/fsnotify.v1.
[WARN]	Unable to checkout github.com/spf13/viper
[ERROR]	Update failed for github.com/spf13/viper: Unable to get repository
[INFO]	--> Fetching gopkg.in/mgo.v2.
[WARN]	Unable to checkout github.com/streamrail/concurrent-map
[ERROR]	Update failed for github.com/streamrail/concurrent-map: Unable to get repository
[INFO]	--> Fetching gopkg.in/square/go-jose.v1.
[WARN]	Unable to checkout github.com/stretchr/objx
[ERROR]	Update failed for github.com/stretchr/objx: Unable to get repository
[INFO]	--> Fetching gopkg.in/yaml.v2.
[WARN]	Unable to checkout github.com/unrolled/render
[ERROR]	Update failed for github.com/unrolled/render: Unable to get repository
[WARN]	Unable to checkout github.com/vdemeester/libkermit
[ERROR]	Update failed for github.com/vdemeester/libkermit: Unable to get repository
[WARN]	Unable to checkout github.com/thoas/stats
[ERROR]	Update failed for github.com/thoas/stats: Unable to get repository
[WARN]	Unable to checkout github.com/vulcand/predicate
[ERROR]	Update failed for github.com/vulcand/predicate: Unable to get repository
[WARN]	Unable to checkout github.com/wendal/errors
[ERROR]	Update failed for github.com/wendal/errors: Unable to get repository
[WARN]	Unable to checkout github.com/vulcand/oxy
[ERROR]	Update failed for github.com/vulcand/oxy: Unable to get repository
[WARN]	Unable to checkout github.com/vulcand/route
[ERROR]	Update failed for github.com/vulcand/route: Unable to get repository
[WARN]	Unable to checkout github.com/vdemeester/shakers
[ERROR]	Update failed for github.com/vdemeester/shakers: Unable to get repository
[WARN]	Unable to checkout github.com/xenolf/lego
[ERROR]	Update failed for github.com/xenolf/lego: Unable to get repository
[WARN]	Unable to checkout github.com/vulcand/vulcand
[ERROR]	Update failed for github.com/vulcand/vulcand: Unable to get repository
[WARN]	Unable to checkout github.com/vdemeester/docker-events
[ERROR]	Update failed for github.com/vdemeester/docker-events: Unable to get repository
[WARN]	Unable to checkout github.com/stretchr/testify
[ERROR]	Update failed for github.com/stretchr/testify: Unable to get repository
[WARN]	Unable to checkout golang.org/x/crypto
[ERROR]	Update failed for golang.org/x/crypto: Unable to get repository
[WARN]	Unable to checkout gopkg.in/alecthomas/kingpin.v2
[ERROR]	Update failed for gopkg.in/alecthomas/kingpin.v2: Unable to get repository
[WARN]	Unable to checkout gopkg.in/fsnotify.v1
[ERROR]	Update failed for gopkg.in/fsnotify.v1: Unable to get repository
[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Unable to get repository
[WARN]	Unable to checkout golang.org/x/sys
[ERROR]	Update failed for golang.org/x/sys: Unable to get repository
[WARN]	Unable to checkout gopkg.in/mgo.v2
[ERROR]	Update failed for gopkg.in/mgo.v2: Unable to get repository
[WARN]	Unable to checkout gopkg.in/square/go-jose.v1
[ERROR]	Update failed for gopkg.in/square/go-jose.v1: Unable to get repository
[WARN]	Unable to checkout gopkg.in/yaml.v2
[ERROR]	Update failed for gopkg.in/yaml.v2: Unable to get repository
[ERROR]	Failed to install: Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
The command '/bin/sh -c glide install' returned a non-zero code: 1
make: *** [build] Error 1

**Comment by ryane** [comment]
I'm a little confused on this issue. That doesn't look like the docker build for this repository. And building the docker image does seem to still work correctly (from master):

```
docker build -t nginx-mantlui .
Sending build context to Docker daemon 14.64 MB
Step 1 : FROM ciscocloud/nginx-consul:1.1
1.1: Pulling from ciscocloud/nginx-consul

a3ed95caeb02: Pull complete 
59f8176db6a0: Pull complete 
a0c94a32b859: Pull complete 
4c33f001aa82: Pull complete 
b79ef3b058af: Pull complete 
adc6a5aaab36: Pull complete 
63e4a92c2b06: Pull complete 
74556a5da29d: Pull complete 
79658ff54138: Pull complete 
ff43fb8253ae: Pull complete 
Digest: sha256:9fd3b923f3c389b5ddd958c09691fef6230dc71921f22d965d2a98269db4f454
Status: Downloaded newer image for ciscocloud/nginx-consul:1.1
 ---> 1b074e45ad63
Step 2 : MAINTAINER Ryan Eschinger <ryanesc@gmail.com>
 ---> Running in ef1cef0980af
 ---> 3057ed0c9216
Removing intermediate container ef1cef0980af
Step 3 : RUN mkdir -p /usr/share/nginx
 ---> Running in 24a5e80bbdba
 ---> 46af11be58dd
Removing intermediate container 24a5e80bbdba
Step 4 : COPY html /usr/share/nginx/html
 ---> f3039029acff
Removing intermediate container 7a3f17a6bfc9
Step 5 : COPY nginx.tmpl /consul-template/templates/
 ---> f219eac4dc52
Removing intermediate container 6b8c561f1444
Step 6 : COPY services.json.tmpl /consul-template/templates/
 ---> dc73cc458265
Removing intermediate container c2bd5fd15a39
Step 7 : COPY consul.cfg /consul-template/config.d/
 ---> 5b88fc646f0f
Removing intermediate container 7f117382a4b9
Successfully built 5b88fc646f0f
```
