### ISSUE TITLE
link directly to /consul/ui to avoid a redirect

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/nginx-mantlui#3]
For consul, if we link directly to `/consul/ui/` we can avoid a redirect and improve the experience.

**Comment by BrianHicks** [comment]
Good point! I'll change the endpoint.

**Comment by ryane** [comment]
I was wrong about this. linking directly to /consul/ui/ results in a 404. I'm not sure we can actually solve this problem as it is the consul frontend application that is manipulating the history on the client side to navigate to something like `/ui/#/vagrant/services`, where `vagrant` is the consul dc.
